#pragma once

enum ErrorNumType
{
	T_SERVER_SUCCESS			= 0,		//处理成功

	//[1000,2000) 为ZoneServer错误
	T_ZONE_ERROR_BASE			= 1000,						//Zone错误码开始
	T_ZONE_PARA_ERROR			= T_ZONE_ERROR_BASE + 1,	//Zone参数错误
	T_ZONE_PROTOBUFF_ERR		= T_ZONE_ERROR_BASE + 2,	//protobuf 错误
	T_ZONE_LOGINSERVER_FAILED	= T_ZONE_ERROR_BASE + 3,	//登录区服务器错误
	T_ZONE_LOGOUT_KICKOFF		= T_ZONE_ERROR_BASE + 4,    //踢人下线错误
	T_ZONE_SESSION_EXISTS_ERR	= T_ZONE_ERROR_BASE + 5,    //玩家的Session已经存在
	T_ZONE_LOGOUT_UNACTIVE		= T_ZONE_ERROR_BASE + 6,    //踢已经不活跃的玩家下线
	T_ZONE_INVALID_CFG			= T_ZONE_ERROR_BASE + 7,    //非法的配置
	T_ZONE_GAMEROLE_NOT_EXIST	= T_ZONE_ERROR_BASE + 8,    //玩家角色信息不存在
	T_ZONE_SECURITY_CHECK_FAILED= T_ZONE_ERROR_BASE + 9,    //传入参数安全校验错误
	T_ZONE_GM_COMMAND_FAILED	= T_ZONE_ERROR_BASE + 10,   //执行GM命令失败
	T_ZONE_INVALID_BULLETNUM	= T_ZONE_ERROR_BASE + 11,   //非法的子弹数目
	T_ZONE_INVALID_NOSILVER		= T_ZONE_ERROR_BASE + 12,   //金币数量不够
	T_ZONE_INVALID_BULLET		= T_ZONE_ERROR_BASE + 13,   //非法的子弹信息
	T_ZONE_INVALID_MAILTYPE		= T_ZONE_ERROR_BASE + 14,   //非法的邮件类型
	T_ZONE_INVALID_SKILLTYPE	= T_ZONE_ERROR_BASE + 15,   //非法的技能类型
	T_ZONE_INVALID_AIMSTAT		= T_ZONE_ERROR_BASE + 16,   //非法的瞄准状态
	T_ZONE_INVALID_FISH			= T_ZONE_ERROR_BASE + 17,   //非法的鱼
	T_ZONE_INVALID_LOTTERYSTEP	= T_ZONE_ERROR_BASE + 18,   //非法的转盘阶段
	T_ZONE_INVALID_GMUSER		= T_ZONE_ERROR_BASE + 19,   //非法的GM用户
	T_ZONE_PERSON_LIMIT			= T_ZONE_ERROR_BASE + 20,	//用户个人限制

	//[2000,3000) 为WorldServer错误
	T_WORLD_ERROR_BASE			= 2000,						//World错误码开始
	T_WORLD_PARA_ERROR			= T_WORLD_ERROR_BASE + 1,	//World参数错误
	T_WORLD_CANNOT_CREATE_ROLE	= T_WORLD_ERROR_BASE + 2,   //World不能创建角色
	T_WORLD_SERVER_BUSY			= T_WORLD_ERROR_BASE + 3,   //World服务器忙
	T_WORLD_SESSION_EXIST		= T_WORLD_ERROR_BASE + 4,   //session已经存在  
	T_WORLD_FETCHROLE_FAIED		= T_WORLD_ERROR_BASE + 5,   //拉取角色数据信息失败 

	//[3000,4000) 为NameDBServer错误
	T_NAMEDB_ERROR_BASE			= 3000,						//NameDB错误码开始
	T_NAMEDB_PARA_ERROR			= T_NAMEDB_ERROR_BASE + 1,	//NameDB参数错误
	T_NAMEDB_NAME_EXISTS		= T_NAMEDB_ERROR_BASE + 2,  //要创建的帐号已经存在

	//[4000,5000) 为RoleDBServer错误
	T_ROLEDB_ERROR_BASE			= 4000,						//RoleDB错误码开始
	T_ROLEDB_PARA_ERR			= T_ROLEDB_ERROR_BASE + 1,  //参数错误
	T_ROLEDB_SQL_EXECUTE_FAILED = T_ROLEDB_ERROR_BASE + 2,  //SQL语句执行失败
	T_ROLEDB_INVALID_RECORD		= T_ROLEDB_ERROR_BASE + 3,  //非法的数据库查询记录

	//[5000,6000) 为RegAuthServer错误
	T_REGAUTH_ERROR_BASE		= 5000,						//RegAuth错误码开始
	T_REGAUTH_PARA_ERROR		= T_REGAUTH_ERROR_BASE + 1,	//RegAuth参数错误
	T_REGAUTH_SERVER_BUSY		= T_REGAUTH_ERROR_BASE + 2, //RegAuth服务器忙

	//[6000,7000) 为RegAuthDBServer错误
	T_REGAUTHDB_ERROR_BASE		= 6000,							//RegAuthDB错误码开始
	T_REGAUTHDB_PARA_ERROR		= T_REGAUTHDB_ERROR_BASE + 1,	//RegAuthDB参数错误
	T_REGAUTHDB_ACCOUNT_EXISTS	= T_REGAUTHDB_ERROR_BASE + 2,	//要创建的帐号已经存在
	T_REGAUTHDB_SQL_FAILED		= T_REGAUTHDB_ERROR_BASE + 3,	//SQL语句执行失败
	T_REGAUTHDB_INVALID_RECORD	= T_REGAUTHDB_ERROR_BASE + 4,	//非法的数据库记录   
	T_REGAUTHDB_INVALID_PASSWD	= T_REGAUTHDB_ERROR_BASE + 5,	//帐号密码错误

	//[7000,8000) 为ExchangeServer错误
	T_EXCHANGE_ERROR_BASE = 7000,						//Exchange错误码开始
	T_EXCHANGE_PARA_ERROR = T_EXCHANGE_ERROR_BASE + 1,	//Exchange参数错误											
};
